"""
This type stub file was generated by pyright.
"""

"""Utility functions used by _session.py.
"""
sqlite_url_prefix = ...
def create_engine(url, **kwargs): # -> Engine:
    """Creates a new SQLAlchemy engine. If ``url`` is a URL for a SQLite database, makes sure that
    the SQLite file exits and enables foreign key constraints.
    """
    ...

