"""
This type stub file was generated by pyright.
"""

"""Sets up logging for the library.
"""
def green(msg): # -> Text:
    ...

def red(msg): # -> Text:
    ...

def yellow(msg): # -> Text:
    ...

