"""
This type stub file was generated by pyright.
"""

class SQLSanitizer:
    """Sanitizes SQL values.
    """
    def __init__(self, dialect) -> None:
        ...
    
    def escape(self, value): # -> TokenList | Token:
        """Escapes value using engine's conversion function.
        https://docs.sqlalchemy.org/en/latest/core/type_api.html#sqlalchemy.types.TypeEngine.literal_processor

        :param value: The value to be sanitized

        :returns: The sanitized value
        """
        ...
    
    def escape_iterable(self, iterable): # -> TokenList:
        """Escapes each value in iterable and joins all the escaped values with ", ", formatted for
        SQL's ``IN`` operator.

        :param: An iterable of values to be escaped

        :returns: A comma-separated list of escaped values from ``iterable``
        :rtype: :class:`sqlparse.sql.TokenList`
        """
        ...
    


def escape_verbatim_colon(value): # -> str:
    """Escapes verbatim colon from a value so as it is not confused with a parameter marker.
    """
    ...

